### ISSUE TITLE
Consistent capitalization for joins

### ISSUE THREAD

**Issue by mmtang** [swamp-fhabs/incident_web_map#1]
In FHAB_BloomReport_Tableau.csv, one of advisory level values is "**Suspected bloom**."

In **advisory_HTML_colors.csv** and **advisory_descriptions.csv**, the same advisory level is "**Suspected Bloom**."

This is not urgent at all, but at some point we should change the capitalization of "bloom" so that it is consistent across all three files.

**Comment by keithbg** [comment]
The standard will be "Suspected bloom." The two CSV files have been changed to "Suspected bloom"
